version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./configs/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: web
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn -w 4 djangoboots.wsgi -b 0.0.0.0:8001'
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8001"
    depends_on:
      - db
  db:
    image: postgres
  